displayName=Bingo Luck Sync
author=IMThorgrim/Thorgrim102
description=Optionally syncs your collection log and raid completions to your group's bingo/luck website.
tags=collection log,raids,luck,gim,tracker,sync
plugins=com.bingoluck.BingoLuckSyncPlugin
build=standard
